/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campusdiary;

import db.Dbcon;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class UpdateCollegeProfile extends javax.swing.JFrame {

    /**
     * Creates new form UpdateCollegeProfile
     */
    public UpdateCollegeProfile() {
        initComponents();
    }
    public UpdateCollegeProfile(String id) {
        initComponents();
        try {
             Dbcon db=new Dbcon();
            
        String sql="select * from tbl_colleges where id='"+id+"'";
        ResultSet rs=db.select(sql);
        if(rs.next()){
            collid.setText(rs.getString(1));
            college.setText(rs.getString(2));
            location.setText(rs.getString(3));
             String temp=rs.getString("branches");
             System.out.println("temp : " + temp);
             String sql1="select * from tbl_branches";
             ResultSet rs1=db.select(sql1);
             while(rs1.next()){
                 String name=rs1.getString("branches");
                 System.out.println("checking : " + name);
                 if(temp.contains(name)){
                     selectedOne.add(name);
                 }else{
                     allBranches.add(name);
                 }
             }
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        selectedOne = new java.awt.List();
        jButton2 = new javax.swing.JButton();
        allBranches = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        college = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        location = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        collid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, -1, -1));
        getContentPane().add(selectedOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 164, 205));

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, 31));

        allBranches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBranchesActionPerformed(evt);
            }
        });
        getContentPane().add(allBranches, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 164, 198));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("UPDATE  COLLEGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 11, 254, -1));

        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, 31));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 48, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, -1, -1));

        college.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegeActionPerformed(evt);
            }
        });
        getContentPane().add(college, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 264, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Allocating Branches");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 129, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Location");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        location.setColumns(20);
        location.setRows(5);
        jScrollPane1.setViewportView(location);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 264, 121));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Id");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 24, 23));

        collid.setEditable(false);
        getContentPane().add(collid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 264, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("F:\\CampusDiary\\img\\staff.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id=collid.getText();
        String name = college.getText();
        String location1 = location.getText();
        String branches = "";
        int i;
        String[] items = selectedOne.getItems();
        for (i = 0; i < items.length; i++) {
            branches = branches + items[i] + ",";
        }
        if (name.equals("") || location1.equals("") || branches.equals("")) {
            JOptionPane.showMessageDialog(this, "enter the values");
        } else {

            Dbcon db = new Dbcon();
            String sql = "update tbl_colleges set name='"+name+"',location='"+location1+"',branches='" + branches + "' where id='"+id+"'";
            int ins = db.insert(sql);
            if (ins > 0) {
                JOptionPane.showMessageDialog(this, "successfully inserted");
                 ViewCollegeProfile college = new ViewCollegeProfile();
        college.setVisible(true);    
        this.dispose();
   
            } else {
                JOptionPane.showMessageDialog(this, "try again");
            }
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String selectedItem = allBranches.getSelectedItem();
        System.out.println(selectedItem);
        if (selectedItem == null) {
            JOptionPane.showMessageDialog(this, "select item");
        } else {
            allBranches.remove(selectedItem);
            selectedOne.add(selectedItem);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void allBranchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBranchesActionPerformed

        String select = allBranches.getSelectedItem();
        if (select == null) {
            JOptionPane.showMessageDialog(this, "select any one");

        } else {
            selectedOne.remove(select);
            allBranches.add(select);
        }
    }//GEN-LAST:event_allBranchesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String selectedlist = selectedOne.getSelectedItem();
        if (selectedlist == null) {
            JOptionPane.showMessageDialog(this, "select item");
        } else {
            selectedOne.remove(selectedlist);
            allBranches.add(selectedlist);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ViewCollegeProfile college = new ViewCollegeProfile();
        college.setVisible(true);    
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void collegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegeActionPerformed

    }//GEN-LAST:event_collegeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCollegeProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCollegeProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCollegeProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCollegeProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCollegeProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List allBranches;
    private javax.swing.JTextField college;
    private javax.swing.JTextField collid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea location;
    private java.awt.List selectedOne;
    // End of variables declaration//GEN-END:variables
}
