/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * UpdateSylabus.java
 *
 * Created on Dec 11, 2016, 12:34:15 AM
 */
package campusdiary;

import db.Dbcon;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class UpdateSylabus extends javax.swing.JFrame {

    /**
     * Creates new form UpdateSylabus
     */
    public UpdateSylabus() {
        initComponents();
       
    }
     private void loadbranch()
    {
        try {
            String sql="select * from tbl_branches" ;
            Dbcon db = new Dbcon();
            ResultSet rs=db.select(sql);
            while (rs.next()) {
                String br= rs.getString(2);
                branch.addItem(br);

            }
        } catch (SQLException ex) {
            Logger.getLogger(AddSylabus.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
       private void loadSubject()
    {
        String sql="select subject_code from tbl_subjects" ;
        Dbcon db = new Dbcon();
        ResultSet rs=db.select(sql);
        try {
            while (rs.next()) {
                String subname = rs.getString(1);
                sub1.addItem(subname);

            }
        } catch (Exception e) {
            System.out.println("subname");
        }
    }
    public UpdateSylabus(String id) {
        initComponents();
         this.setLocationRelativeTo(null);
        loadSubject();
        loadbranch();
        
        Dbcon db = new Dbcon();
        String sql="select * from tbl_sylabus where id='"+id+"'";
        ResultSet rs = db.select(sql);
        System.out.println(rs);
        try {
            if (rs.next()) {
              sylabusid.setText(rs.getString(1));
                revcode.setText(rs.getString(2));
                mod1.setText(rs.getString("module_1"));
                mod2.setText(rs.getString("module_2"));
                mod3.setText(rs.getString("module_3"));
                mod4.setText(rs.getString("module_4"));
                refe.setText(rs.getString("reference"));
                sub1.setSelectedItem(rs.getString("subject_code"));
                branch.setSelectedItem(rs.getString("branch"));
                sem.setSelectedItem(rs.getString("semester"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateSylabus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mod1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        mod3 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        refe = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        mod2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        mod4 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sem = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        revcode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        subname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        branch = new javax.swing.JComboBox();
        sub1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        sylabusid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Module 1");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 139, 116, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Module 4");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 394, 116, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText(" UPDATE SYLLABUS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 38, 320, 27));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Module 3");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 304, 116, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Module 2");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 225, 116, -1));

        submit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        submit.setText("UPDATE");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 475, -1, -1));

        mod1.setColumns(20);
        mod1.setRows(5);
        jScrollPane1.setViewportView(mod1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 124, 217, 63));

        mod3.setColumns(20);
        mod3.setRows(5);
        jScrollPane2.setViewportView(mod3);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 293, 217, 68));

        refe.setColumns(20);
        refe.setRows(5);
        jScrollPane3.setViewportView(refe);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 464, 217, 74));

        mod2.setColumns(20);
        mod2.setRows(5);
        jScrollPane4.setViewportView(mod2);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 205, 217, 68));

        mod4.setColumns(20);
        mod4.setRows(5);
        jScrollPane5.setViewportView(mod4);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 379, 217, 67));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("References");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 469, 82, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Semester ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 410, 116, -1));

        sem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        sem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--select--", "semester 1", "semster 2", "semester 3", "semester 4", "semester 5", "semester 6" }));
        sem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semActionPerformed(evt);
            }
        });
        getContentPane().add(sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 409, 170, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Revision Code       ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 174, -1, -1));
        getContentPane().add(revcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 174, 170, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Branch                 ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 253, 116, -1));

        subname.setEditable(false);
        subname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subnameActionPerformed(evt);
            }
        });
        getContentPane().add(subname, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 352, 170, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Subject  Code       ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 303, 126, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Subject Name       ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 355, 116, -1));

        branch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchActionPerformed(evt);
            }
        });
        getContentPane().add(branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 252, 170, -1));

        sub1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sub1ItemStateChanged(evt);
            }
        });
        sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub1ActionPerformed(evt);
            }
        });
        getContentPane().add(sub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 302, 170, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 127, -1, -1));

        sylabusid.setEditable(false);
        getContentPane().add(sylabusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 124, 170, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 475, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\kakes\\Documents\\NetBeansProjects\\poli\\CampusDiary\\img\\staff.png")); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
    String revision = revcode.getText();
    String iid=sylabusid.getText();
    String branchname = branch.getSelectedItem().toString();
    String semestar = sem.getSelectedItem().toString();
    String subjectcode = sub1.getSelectedItem().toString();
    String subject = subname.getText();
    String module1=mod1.getText();
    String module2=mod2.getText();
    String module3=mod3.getText();
    String module4=mod4.getText();
    String references=refe.getText();
    int k=sem.getSelectedIndex();
if(iid.equals("")||revision.equals("")||references.equals("")||k==0||module1.equals("")||module2.equals("")||module3.equals("")||module4.equals("")){
        JOptionPane.showMessageDialog(this, "enter the values");
    }else{
    
    Dbcon db = new Dbcon();
     String sql = "update tbl_sylabus set revision_code='"+revision+"',branch='"+branchname+"',semester='"+semestar+"',subject_code='"+subjectcode+"',subject_name='"+subject+"',module_1='"+module1+"',module_2='"+module2+"',module_3='"+module3+"',module_4='"+module4+"',reference='"+references+"' where id='"+iid+"'";
           int ins= db.update(sql);
           if(ins>0){
               JOptionPane.showMessageDialog(this, "successfully inserted");
               ViewSylabus sylabus=new ViewSylabus();
                   sylabus.setVisible(true);
                    this.dispose();
               
           }else{
               JOptionPane.showMessageDialog(this, "try again");
           }
    }
    

}//GEN-LAST:event_submitActionPerformed

    private void semActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semActionPerformed

    private void subnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subnameActionPerformed

    private void branchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchActionPerformed

    private void sub1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sub1ItemStateChanged

        String subc = sub1.getSelectedItem().toString();
        Dbcon db = new Dbcon();
        ResultSet rs = db.select("select subject_name from tbl_subjects where subject_code ='" + subc + "'");
        try {
            if(rs.next()){
                subname.setText(rs.getString("subject_name"));
            }
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(AddSylabus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sub1ItemStateChanged

    private void sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            ViewSylabus sylabus=new ViewSylabus();
                   sylabus.setVisible(true);
                    this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateSylabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateSylabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateSylabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateSylabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UpdateSylabus().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox branch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea mod1;
    private javax.swing.JTextArea mod2;
    private javax.swing.JTextArea mod3;
    private javax.swing.JTextArea mod4;
    private javax.swing.JTextArea refe;
    private javax.swing.JTextField revcode;
    private javax.swing.JComboBox sem;
    private javax.swing.JComboBox sub1;
    private javax.swing.JButton submit;
    private javax.swing.JTextField subname;
    private javax.swing.JTextField sylabusid;
    // End of variables declaration//GEN-END:variables
}
