/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staff;

import db.Dbcon;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class AddTimeTable extends javax.swing.JFrame {

    /**
     * Creates new form AddTimeTable
     */
    public AddTimeTable() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadbranch();
        loadsubject();
    }

    private void loadbranch() {
        try {
            String sql = "select * from tbl_branches;";
            Dbcon db = new Dbcon();
            ResultSet rs = db.select(sql);
            while (rs.next()) {
                String br = rs.getString(2);
                branch.addItem(br);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddTimeTable.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadsubject() {
        String sql = "select * from tbl_subjects;";
        Dbcon db = new Dbcon();
        ResultSet rs = db.select(sql);
        try {
            while (rs.next()) {
                String sub = rs.getString(2);
                subjectCode.addItem(sub);

            }
        } catch (SQLException ex) {
            Logger.getLogger(AddTimeTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        branch = new javax.swing.JComboBox<>();
        semester = new javax.swing.JComboBox<>();
        subjectCode = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        subjectName = new javax.swing.JTextField();
        hour = new javax.swing.JSpinner();
        minute = new javax.swing.JSpinner();
        meridian = new javax.swing.JButton();
        date = new org.jdesktop.swingx.JXDatePicker();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("SERIES TIME TABLE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 31, -1, 27));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Branch");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 106, 53, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Semester");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 157, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 210, 58, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Time");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 265, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Subject code");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 312, 98, -1));

        back.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 449, -1, -1));

        submit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 449, -1, -1));

        branch.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        getContentPane().add(branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 105, 190, -1));

        semester.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "semester 1", "semester 2", "semester 3", "semester 4", "semester 5", "semester 6" }));
        getContentPane().add(semester, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 154, 190, -1));

        subjectCode.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        subjectCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                subjectCodeItemStateChanged(evt);
            }
        });
        subjectCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectCodeActionPerformed(evt);
            }
        });
        getContentPane().add(subjectCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 309, 185, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Subject Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 362, 113, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 365, 147, -1));

        subjectName.setEditable(false);
        subjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectNameActionPerformed(evt);
            }
        });
        getContentPane().add(subjectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 356, 185, -1));

        hour.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        getContentPane().add(hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 259, -1, -1));

        minute.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        getContentPane().add(minute, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 259, 53, -1));

        meridian.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        meridian.setText("am");
        meridian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meridianActionPerformed(evt);
            }
        });
        getContentPane().add(meridian, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 261, -1, -1));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 204, 190, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("F:\\CampusDiary\\img\\staff.png")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:

        String br = branch.getSelectedItem().toString();
        String sem = semester.getSelectedItem().toString();
        String da = date.getDate().toString();
        String hr = hour.getValue().toString();
        String mi = minute.getValue().toString();
        String me = meridian.getText();
        String ti = hr + ":" + mi + ":" + me;
        String sub = subjectCode.getSelectedItem().toString();
        String subn = subjectName.getText();
        int i = semester.getSelectedIndex();

        if (i == 0 || date.getDate() == null || ti.equals("")) {
            JOptionPane.showMessageDialog(this, "please enter the values");
        } else {
            Dbcon db = new Dbcon();
            long milli = date.getDate().getTime();
            String sql = "insert into tbl_series_time_table(branch,semester,subject_code,subject_name,date,time,college_id,date_milli)values('" + br + "','" + sem + "','" + sub + "','" + subn + "','" + da + "','" + ti + "', '" + StaffLogin.collegeId + "','" + milli + "');";
            System.out.println(sql);

            int ins = db.insert(sql);
            if (ins > 0) {
                JOptionPane.showMessageDialog(rootPane, "Success");

            } else {
                JOptionPane.showMessageDialog(rootPane, "Could not insert");

            }
        }
        // TODO add your handling code here:

    }//GEN-LAST:event_submitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        StaffHomePage hp = new StaffHomePage();
        hp.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void subjectCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectCodeActionPerformed

    private void subjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectNameActionPerformed
    }//GEN-LAST:event_subjectNameActionPerformed

    private void subjectCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_subjectCodeItemStateChanged

        try {
            // TODO add your handling code here:
            String subc = subjectCode.getSelectedItem().toString();
            Dbcon db = new Dbcon();
            ResultSet rs = db.select("select subject_name from tbl_subjects where subject_code ='" + subc + "'");
            if (rs.next()) {
                subjectName.setText(rs.getString("subject_name"));
            }

        } catch (SQLException ex) {
            System.out.println(ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectCodeItemStateChanged

    private void meridianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meridianActionPerformed
        // TODO add your handling code here:
        String me = meridian.getText();
        if (me.equals("am")) {
            meridian.setText("pm");
        } else {
            meridian.setText("am");
        }
    }//GEN-LAST:event_meridianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AddTimeTable().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> branch;
    private org.jdesktop.swingx.JXDatePicker date;
    private javax.swing.JSpinner hour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton meridian;
    private javax.swing.JSpinner minute;
    private javax.swing.JComboBox<String> semester;
    private javax.swing.JComboBox<String> subjectCode;
    private javax.swing.JTextField subjectName;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
