/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staff;

import db.Dbcon;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ViewSylabus extends javax.swing.JFrame {

        DefaultTableModel model=null;
    String id;
    /**
     * Creates new form ViewSylabus
     */
    public ViewSylabus() {
        initComponents();
        this.setLocationRelativeTo(null);
        viewsylabus();
    }
    private void viewsylabus(){
        try {

        Dbcon db=new Dbcon();
        model = (DefaultTableModel)sylabus.getModel();
        String array[]=new String[11];
        String sql="select * from tbl_sylabus";
        ResultSet rs=db.select(sql);
        while(rs.next()){
            String id = rs.getString(1);
            String code=rs.getString(2);
            String branch=rs.getString(3);
            String sem=rs.getString(4);
            String subcode=rs.getString(5);
            String sub=rs.getString(6);
            array[0]=id;
            array[1]=code;
            array[2]=branch;
            array[3]=sem;
            array[4]=subcode;
            array[5]=sub;
            model.addRow(array);
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"error in viewing");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sylabus = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        mode1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        mode2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        mode3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        mode4 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ref = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton6.setText("BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 549, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("VIEW SYLLABUS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 29, 220, -1));

        sylabus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        sylabus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Revision_code", "Branch", "Semester", "Subject_code", "Subject"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sylabus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sylabusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sylabus);
        if (sylabus.getColumnModel().getColumnCount() > 0) {
            sylabus.getColumnModel().getColumn(0).setMinWidth(0);
            sylabus.getColumnModel().getColumn(0).setPreferredWidth(0);
            sylabus.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 75, 521, 313));

        mode1.setColumns(20);
        mode1.setEditable(false);
        mode1.setRows(5);
        jScrollPane2.setViewportView(mode1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 75, -1, -1));

        mode2.setColumns(20);
        mode2.setEditable(false);
        mode2.setRows(5);
        jScrollPane3.setViewportView(mode2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 198, -1, -1));

        mode3.setColumns(20);
        mode3.setEditable(false);
        mode3.setRows(5);
        jScrollPane4.setViewportView(mode3);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 312, -1, -1));

        mode4.setColumns(20);
        mode4.setEditable(false);
        mode4.setRows(5);
        jScrollPane5.setViewportView(mode4);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 426, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Module 1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 111, 57, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Module 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 215, 57, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Module 3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 331, 57, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Module 4");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 448, 57, -1));

        ref.setColumns(20);
        ref.setEditable(false);
        ref.setRows(5);
        jScrollPane6.setViewportView(ref);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("References");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 439, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("F:\\CampusDiary\\img\\staff.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        StaffHomePage staffhome = new StaffHomePage();
        staffhome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void sylabusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sylabusMouseClicked

        model=(DefaultTableModel)sylabus.getModel();
        if(model.getValueAt(sylabus.getSelectedRow(),0).toString().equals("")){
            JOptionPane.showMessageDialog(this,"no data selected");

        }
        else
        {
            id=model.getValueAt(sylabus.getSelectedRow(),0).toString();
            try {
                 Dbcon db=new Dbcon();
            String sql="select module_1,module_2,module_3,module_4,reference from tbl_sylabus where id='"+id+"'";
            ResultSet rs=db.select(sql);
            if(rs.next()){
                mode1.setText(rs.getString(1));
                mode2.setText(rs.getString(2));
                mode3.setText(rs.getString(3));
                mode4.setText(rs.getString(4));
                ref.setText(rs.getString(5));
            }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_sylabusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSylabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSylabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSylabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSylabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSylabus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea mode1;
    private javax.swing.JTextArea mode2;
    private javax.swing.JTextArea mode3;
    private javax.swing.JTextArea mode4;
    private javax.swing.JTextArea ref;
    private javax.swing.JTable sylabus;
    // End of variables declaration//GEN-END:variables
}
